ZGVidWcgPSB0cnVlCgpbYXBwXQp2aWRlb19zb3VyY2UgPSAicGV4ZWxzIgpwZXhlbHNfYXBpX2tl
eXMgPSBbICJNaEhSMFFGVVc3cEZjMXdpcnZabXRrdllPWlp6NTg1QzZvTFdDSVFIRnZmQnVBdVli
YjNxQ2dXaiIsXQpwaXhhYmF5X2FwaV9rZXlzID0gWyAiMjMwNTg0NzUtNjllNGVjZWQwY2VkYmVm
ZWE5NmQ4ZmFjYiIsXQpsbG1fcHJvdmlkZXIgPSAibW9vbnNob3QiCm9sbGFtYV9iYXNlX3VybCA9
ICIiCm9sbGFtYV9tb2RlbF9uYW1lID0gIiIKb3BlbmFpX2FwaV9rZXkgPSAiIgpvcGVuYWlfYmFz
ZV91cmwgPSAiIgpvcGVuYWlfbW9kZWxfbmFtZSA9ICJncHQtNC10dXJibyIKbW9vbnNob3RfYXBp
X2tleSA9ICJzay12ZHhoNVRSeGx2ZTdiNXIyeEpDa2h5R0hHSzB6dUN5QTl3Y3NCTVNadFQxRmNm
QlQiCm1vb25zaG90X2Jhc2VfdXJsID0gImh0dHBzOi8vYXBpLm1vb25zaG90LmNuL3YxIgptb29u
c2hvdF9tb2RlbF9uYW1lID0gIm1vb25zaG90LXYxLThrIgpvbmVhcGlfYXBpX2tleSA9ICJzay12
ZHhoNVRSeGx2ZTdiNXIyeEpDa2h5R0hHSzB6dUN5QTl3Y3NCTVNadFQxRmNmQlQiCm9uZWFwaV9i
YXNlX3VybCA9ICIiCm9uZWFwaV9tb2RlbF9uYW1lID0gIiIKZzRmX21vZGVsX25hbWUgPSAiZ3B0
LTMuNS10dXJibyIKYXp1cmVfYXBpX2tleSA9ICIiCmF6dXJlX2Jhc2VfdXJsID0gIiIKYXp1cmVf
bW9kZWxfbmFtZSA9ICJncHQtMzUtdHVyYm8iCmF6dXJlX2FwaV92ZXJzaW9uID0gIjIwMjQtMDIt
MTUtcHJldmlldyIKZ2VtaW5pX2FwaV9rZXkgPSAiIgpnZW1pbmlfbW9kZWxfbmFtZSA9ICJnZW1p
bmktMS4wLXBybyIKcXdlbl9hcGlfa2V5ID0gIiIKcXdlbl9tb2RlbF9uYW1lID0gInF3ZW4tbWF4
IgpkZWVwc2Vla19hcGlfa2V5ID0gIiIKZGVlcHNlZWtfYmFzZV91cmwgPSAiaHR0cHM6Ly9hcGku
ZGVlcHNlZWsuY29tIgpkZWVwc2Vla19tb2RlbF9uYW1lID0gImRlZXBzZWVrLWNoYXQiCnN1YnRp
dGxlX3Byb3ZpZGVyID0gImVkZ2UiCmVuZHBvaW50ID0gIiIKbWF0ZXJpYWxfZGlyZWN0b3J5ID0g
IiIKZW5hYmxlX3JlZGlzID0gdHJ1ZQpyZWRpc19ob3N0ID0gIjE3Mi4xNi4yLjIzNiIKcmVkaXNf
cG9ydCA9IDYzNzkKcmVkaXNfZGIgPSAwCnJlZGlzX3Bhc3N3b3JkID0gIiIKbWF4X2NvbmN1cnJl
bnRfdGFza3MgPSA1CmhpZGVfY29uZmlnID0gZmFsc2UKClt3aGlzcGVyXQptb2RlbF9zaXplID0g
ImxhcmdlLXYzIgpkZXZpY2UgPSAiQ1BVIgpjb21wdXRlX3R5cGUgPSAiaW50OCIKCltvc3NdCmlk
ID0gIkxUQUk1dDg4SlRneXdTdkJoZU5NTUxYYiIKc2VjcmV0ID0gIlR3dHpFcXlGa1N1M3NqOFRH
OHBvdm83YXlsU0NYaiIKZW5kX3BvaW50ID0gImh0dHBzOi8vb3NzLWNuLWJlaWppbmcuYWxpeXVu
Y3MuY29tIgpidWNrZXQgPSAiY2hhbmEtdmlkZW8iCgpbcHJveHldCgpbYXp1cmVdCnNwZWVjaF9r
ZXkgPSAiIgpzcGVlY2hfcmVnaW9uID0gIiIKClt1aV0KbGFuZ3VhZ2UgPSAiZW4iCnZvaWNlX25h
bWUgPSAiemgtQ04tWXVueGlOZXVyYWwtTWFsZSIKZm9udF9uYW1lID0gIk1pY3Jvc29mdFlhSGVp
Qm9sZC50dGMiCnRleHRfZm9yZV9jb2xvciA9ICIjRkZGRkZGIgpmb250X3NpemUgPSA2MApoaWRl
X2xvZyA9IGZhbHNlCg==
