name: MoneyPrintTurbo workflow for staging
run-name: ${{ github.actor }} is CI/CD for MoneyPrintTurbo stagingActions 🚀
on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }} and base."
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - run: echo dev.toml | base64 --decode > config.toml
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "start to setup Docker build"
      - run: echo "TAG_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV   
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to ACR
        uses: aliyun/acr-login@v1
        with:
          login-server: https://registry.cn-beijing.aliyuncs.com
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Build and push image
        run: |
          echo "push version ${{env.TAG_VERSION}}"
          docker build -t registry.cn-beijing.aliyuncs.com/chana/moneyprinterturbo:dev-${{env.TAG_VERSION}} .
          docker push registry.cn-beijing.aliyuncs.com/chana/moneyprinterturbo:dev-${{env.TAG_VERSION}}
      - run: echo "🍏 This job's status is ${{ job.status }}."

  deploy-staging: 
    name: deploy to staging environment
    environment: dev
    runs-on: ubuntu-latest
    needs: build
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "start to setup Docker build"
      - run: echo "TAG_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV   

      - name: start to deploy to dev environment
        run: echo "Complete."
